import { Chivo_Mono } from "next/font/google";
import "./globals.css";

const Chivo = Chivo({

  subsets: ["latin"],
});

const ChivoMono = Chivot_Mono({
  subsets: ["latin"],
});
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={`${Chivo.className} ${ChivoMono.className}`}>
        {children}
      </body>
    </html>
  );
}
